version: 2

jobs:
  trigger_netlify:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - run:
          name: Trigger Netlify build
          command: |
            curl -X POST -d {} https://api.netlify.com/build_hooks/$NETLIFY_KEY
  publish:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  update_netlify:
    jobs:
      - trigger_netlify:
          filters:
             branches:
              only:
                - master
  auto_publish:
    jobs:
      - publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
